<?php
return array(
    "fr" => "Français",
    "en" => "Anglais",
    "pt" => "Portuguais",
    "name" => "Carrilho",
    "first name" => "Joakim",
    "cv" => "CV",
    "webdev title" => "DÉVELOPPEUR <span>WEB</span>",
    "home" => "Accueil",
    "about" => "À propos",
    "resume" => "Résumé",
    "skills" => "Compétences",
    "works" => "Travaux",
    "contact" => "Contact",
    "lang" => "Langue",
    "about me" => "À propos de moi",
    "first name" => "Prénom",
    "name" => "Nom",
    "birthday" => "Date de naissance",
    "adresse" => "Adresse",
    "phone" => "Téléphone",
    "email" => "Email",
    "local_adresse" => "2 rue João de Barros, 2855 Costa De Caparica, Setúbal, Portugal",
    "local_phone" => "+351 999 999 999",
    "mon cv" => "Mon CV",
    "about me title" => "Qui suis-je ?",
    "about me description" => "<p>Nouveau venu dans ce magnifique pays qu'est le Portugal, 
            je suis actuellement à la recherche d'un emploi comme développeur dans la région de Lisbonne.</p> 
        <p>Passionné d'informatique depuis mon plus jeune âge, titulaire d'un BAC+2 Infoformatique de Gestion option Développement d'application depuis 8 ans, 
            et pratiquant la programmation depuis 10 ans, je dispose d'un large panel de compétences,
            aussi bien dans le développement back-end (PHP, Mysql, CMS, API, Administration de serveur), 
            qu'en développement front-end (HTML 5, CSS 3, Javascript/Jquery, Responsive, SEO).</p>",
    "cv pdf" => "CV format PDF",
    "experiences" => "Expériences",
    "france" => "France",
    "webdev fullstack" => "Développeur Web Full Stack",
    "arociel description" => "<p>Développement de site Web, avec et sans outil de gestion de contenu (Wordpress, Drupal).</p>"
    . "<p>Création de site intranet de gestion sur mesure pour différent types de clients (cabinet de gestion immobilière, cabinet d'avocat, imprimerie, association sportive, association écologique, ect).</p>"
    . "<p>Développeur principal d'un Framework HTML5/PHP à la base d'un ERP modulable (ORM, MVC, ACL, metaprogrammation, sécurité, scalabilité, mise à jour automatisé, ect)</p>",
    "freelancer" => "Freelancer",
    "freedev" => "Développeur Freelancer",
    "dev" => "Développeur",
    "freelancer description" => "<p>Création de divers sites web pour collèges et lycées avec système de gestion de contenu (MODx, Drupal).</p>"
    . "<p>Création d'un logiciel de gestion des passages en restauration scolaire (Python, JAVA, swing).</p>"
    . "<p>Mise en place d'un logiciel de visualisation d'information scolaire, sur télévision grand écran (Adobe AIR, HTML5, PHP).</p>",
    
    "formation informatique" => "BAC+2 Infoformatique de Gestion option Développement d'application",
    "formation informatique description" => "<p>Ce diplôme forme des techniciens capables de gérer un parc informatique ou d'administrer un réseau en PME.</p>"
    . "<p>Leur mission consiste alors à automatiser et rationaliser les activités administratives de l'entreprise.</p>"
    . "<p>Il possède des savoirs et savoir-faire en informatique générale et télécommunications, conception de systèmes d'information, bases de données, méthodes et outils de développement des applications, ainsi qu'en gestion des organisations.</p>",
    "formation economie" => "BAC+2 sciences économique et de gestion (Niveau)",
    "formation economie description" => "<p>L'économie est une des pièces maîtresses de la vie en société.</p>"
    . "<p>Que ce soit la macroéconomie qui permet de comprendre le monde à l'echelle des pays, les politiques économique des états, ou la microéconomie qui analyse les comportements des individus ou des entreprises et leurs choix dans le domaine de la production.</p>",
    "universite maine" => "Université du Maine",
    "skills front" => "Développement client",
    "skills back" => "Développement serveur",
    "skills langage system desktop" => "Langage système/desktop",
    "skills other" => "Autres compétences",
    "do contact" => "Prendre contact",
    "contact nom" => "Votre nom",
    "contact mail" => "Votre adresse mail",
    "contact sujet" => "Sujet du message",
    "contact message" => "Votre message",
    "contact envoyer" => "Envoyer",
    "citation" => "Citation",
    "citation text" => "La vie, c’est comme une bicyclette, il faut avancer pour ne pas perdre l’équilibre.", 
    "contact error" => "<strong>Erreur!</strong> Erreur interne, impossible d\'envoyer votre mail.",
    "contact warning" => "<strong>Attention!</strong>",
    "contact success" => "<strong>Réussi!</strong> Votre message est bien parti.",
);